### ISSUE TITLE
App crashed during Google login

### ISSUE THREAD

**Issue by finetard** [iith-dashboard/IITH-Dashboard-frontend#2] opened 2019-09-30 13:54 UTC
On first run, during google login app crashed. But on restarting was logged in and additional features were accessible.
Could not reproduce the issue on later logins.

**Comment by AdaephonBen** [comment] 2019-10-01 09:19
We've updated the app since then, and have added multiple crash fixes. After updating the app, please try to clear the cache and storage and then try to reproduce the issue.

**Comment by finetard** [comment] 2019-10-01 12:52
I have the version downloaded from app store. There is no update for it yet. 
Tried it again after clearing cache. Was able to reproduce the bug.

Clear cache, login with google, select mess(LDH), select running segment (3-4). And the app crashes


By mistake I closed the issue, sorry

**Comment by npalladium** [comment] 2019-10-15 21:07
@finetard, closing this issue. 
If the problem persists please file another issue using the bug template.

**Closed as completed by npalladium** 2019-10-15 21:07 UTC
